name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Clean old build files
        run: rm -rf dist

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create static site directory
        run: |
          mkdir -p static-site
          cp -r dist/assets static-site/
          cp dist/index.html static-site/
          # Don't copy server-side code (index.js)

      - name: Verify Static Site Output
        run: ls -R static-site/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: './static-site'
          compression-level: 9
          if-no-files-found: error

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
